CREATE SCHEMA IF NOT EXISTS GameRater;
USE GameRater;

DROP TABLE IF EXISTS GameIsGenre;
DROP TABLE IF EXISTS GameOnPlatform;
DROP TABLE IF EXISTS UserHasGame;
DROP TABLE IF EXISTS CriticReviews;
DROP TABLE IF EXISTS UserReviews;
DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS Games;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Platforms;
DROP TABLE IF EXISTS Publishers;
DROP TABLE IF EXISTS Genres;

CREATE TABLE Platforms (
  PlatformId INT NOT NULL UNIQUE AUTO_INCREMENT,
  PlatformName VARCHAR(50) NOT NULL UNIQUE,
  CONSTRAINT PlatformPk
    PRIMARY KEY (PlatformId)
) ENGINE = InnoDB;

CREATE TABLE Publishers (
  PublisherId INT NOT NULL UNIQUE AUTO_INCREMENT,
  PublisherName VARCHAR(255) NOT NULL UNIQUE,
  CONSTRAINT PublisherPk
    PRIMARY KEY (PublisherId)
) ENGINE = InnoDB;

CREATE TABLE Genres (
  GenreId INT NOT NULL UNIQUE AUTO_INCREMENT,
  Genre VARCHAR(255) UNIQUE,
  CONSTRAINT GenresPk
    PRIMARY KEY (GenreId)
) ENGINE = InnoDB;

CREATE TABLE Users (
  UserId INT NOT NULL UNIQUE AUTO_INCREMENT,
  SteamId INT UNIQUE,
  UserName TEXT DEFAULT NULL,
  CONSTRAINT UserPk
    PRIMARY KEY (UserId)
) ENGINE = InnoDB;

CREATE TABLE Games (
  GameId INT NOT NULL UNIQUE AUTO_INCREMENT,
  GameName VARCHAR(255) NOT NULL UNIQUE,
  PublisherIdFk INT,
  ReleaseYear INT,
  CONSTRAINT GamesPk
    PRIMARY KEY (GameId),
  CONSTRAINT GamesPublishersFk
    FOREIGN KEY (PublisherIdFk)
    REFERENCES Publishers (PublisherId)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE = InnoDB;

CREATE TABLE UserHasGame (
  UserIdFk INT NOT NULL,
  GameIdFk INT NOT NULL,
  PlayTime FLOAT,
  CONSTRAINT UserHasGamePk
    UNIQUE (UserIdFk, GameIdFk),
  CONSTRAINT UserHasGameUsersFk
    FOREIGN KEY (UserIdFk)
    REFERENCES Users (UserId)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT UserHasGameGamesFk
    FOREIGN KEY (GameIdFk)
    REFERENCES Games (GameId)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE GameIsGenre (
  GameIdFk INT NOT NULL,
  GenreIdFk INT NOT NULL,
  CONSTRAINT GameIsGenreGamesFk
    FOREIGN KEY (GameIdFk)
    REFERENCES Games (GameId)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT GameIsGenreGenresFk
    FOREIGN KEY (GenreIdFk)
    REFERENCES Genres (GenreId)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE GameOnPlatform (
  GameIdFk INT NOT NULL,
  PlatformIdFk INT NOT NULL,
  CONSTRAINT GameOnPlatformGamesFk
    FOREIGN KEY (GameIdFk)
    REFERENCES Games (GameId)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT GameOnPlatformGenresFk
    FOREIGN KEY (PlatformIdFk)
    REFERENCES Platforms (PlatformId)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE Reviews (
  ReviewId INT NOT NULL UNIQUE AUTO_INCREMENT,
  GameIdFK INT NOT NULL,
  Review TEXT,
  CONSTRAINT ReviewsGamesFK
    FOREIGN KEY (GameIdFk)
    REFERENCES Games (GameId)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB;


CREATE TABLE UserReviews (
  ReviewIdFk INT NOT NULL,
  UserIdFk INT NOT NULL,
  Score FLOAT,
  CONSTRAINT UserReviewsReviewFk
    FOREIGN KEY (ReviewIdFk)
    REFERENCES Reviews (ReviewId)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT UserReviewsUsersFk
    FOREIGN KEY (UserIdFk)
    REFERENCES Users (UserId)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE CriticReviews (
  ReviewIdFk INT NOT NULL,
  CriticName VARCHAR(255),
  Score FLOAT,
  CONSTRAINT CriticReviewsReviewFk
    FOREIGN KEY (ReviewIdFk)
    REFERENCES Reviews (ReviewId)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB;